# Generated by Django 4.1.5 on 2023-01-28 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=50)),
                ('ProfileImage', models.ImageField(default='avatar.png', upload_to='profiles/')),
                ('Gender', models.CharField(max_length=10)),
                ('BirthDate', models.DateField(default='1990-01-01')),
                ('State', models.CharField(blank=True, default='', max_length=30)),
                ('City', models.CharField(blank=True, default='', max_length=30)),
                ('HomeAddress', models.CharField(blank=True, default='', max_length=30)),
                ('OfficeAddress', models.CharField(blank=True, default='', max_length=30)),
                ('OtherAddress', models.CharField(blank=True, default='', max_length=30)),
                ('Pincode', models.CharField(blank=True, default='', max_length=6)),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=12)),
                ('IsActive', models.BooleanField(default=False)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('DateModified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ProductQuantity', models.CharField(max_length=50)),
                ('ProductDescription', models.TextField(max_length=250)),
                ('ProductImage', models.ImageField(upload_to='Upload/Products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EShop.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EShop.customers')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EShop.product')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
        migrations.AddField(
            model_name='customers',
            name='Master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EShop.master'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EShop.customers')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EShop.product')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
